repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      exclude: populate_db.py

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-executables-have-shebangs
    -   id: end-of-file-fixer
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670
    hooks:
    - id: mypy
      args: [--config-file=mypy.ini, --ignore-missing-imports]
