version: '3'

services:
  updater:
    image: iomirea/updater
    container_name: updater
    volumes:
      - ../config:/config
      - ../api:/api
      - .:/code
    ports:
      - 8081:8081
    restart: unless-stopped

  registrator:
    image: gliderlabs/registrator
    command: "consul://localhost:8500"
    container_name: registrator
    network_mode: host
    depends_on:
      - consul_client
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped

  consul_client:
    image: consul
    command: "agent -node=${HOSTNAME} -bind=${EXTERNAL_IP} -retry-join=${CONSUL_CLUSTER_IP}"
    container_name: consul_client
    network_mode: host
    volumes:
      - ../consul/client/data:/consul/data
    restart: unless-stopped
